project_id = "hekgkfdunwpxqbrotfpn"

[functions.send-consolidated-reminder]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.manage-staff]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.send-ayn-support]
verify_jwt = false

[functions.generate-employee-badge]
verify_jwt = false

[functions.send-hours-announcement]
verify_jwt = false

[functions.send-staff-credentials]
verify_jwt = false

[functions.send-vip-invitation]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false

[functions.verify-moyasar-payment]
verify_jwt = false

[functions.log-payment-failure]
verify_jwt = false