project_id = "hekgkfdunwpxqbrotfpn"

[functions.send-booking-confirmation]
verify_jwt = false

[functions.manage-staff]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false
